# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec — portable one-file EXE for Pics2PPT."""

from pathlib import Path

block_cipher = None
root = Path(SPECPATH)

a = Analysis(
    [str(root / "pics2ppt_entry.py")],
    pathex=[str(root)],
    binaries=[],
    datas=[
        (str(root / "assets" / "app_icon_256.png"), "assets"),
        (str(root / "assets" / "pics2ppt_logo.png"), "assets"),
        (str(root / "icon.ico"), "."),
    ],
    hiddenimports=[
        "app",
        "app.bootstrap",
        "app.resources",
        "app.core",
        "app.core.scanner",
        "app.core.pptx_builder",
        "app.core.image_processor",
        "app.core.worker",
        "app.core.models",
        "app.core.output_paths",
        "app.services",
        "app.services.settings",
        "app.services.language_prefs",
        "app.i18n",
        "app.i18n.catalog_fa",
        "app.i18n.catalog_en",
        "app.i18n.help_content",
        "app.i18n.locale_detect",
        "app.ui",
        "app.ui.main_window",
        "app.ui.theme",
        "app.ui.fonts",
        "app.ui.layout_direction",
        "app.ui.widgets",
        "app.ui.help_panel",
        "app.ui.language_dialog",
        "app.ui.drop_line_edit",
        "app.ui.pages.home_page",
        "app.ui.pages.settings_page",
        "app.ui.pages.about_page",
        "pptx",
        "pptx.action",
        "pptx.enum.text",
        "pptx.oxml",
        "lxml",
        "lxml.etree",
        "PIL",
        "PIL.Image",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=["tkinter", "matplotlib", "numpy", "PyQt5", "PyQt6"],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="Pics2PPT",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[
        "python*.dll",
        "Qt6*.dll",
        "opengl32sw.dll",
        "pics2ppt_entry.py",
    ],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=str(root / "icon.ico") if (root / "icon.ico").is_file() else None,
)
